services:
  db:
    image: postgres:15-alpine
    container_name: machinery_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: machinery
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: machinery_api
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_DATABASE: machinery
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: machinery_frontend
    restart: always
    depends_on:
      - api
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
